name: json2entity
description: A tool for converting JSON strings into dart entity classes. Support json_serializable.
version: 1.0.5
author: zhouweixian <laxian2010@gmail.com>
homepage: https://github.com/laxian/dart-json2entity


environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  args: ^1.5.1
  path: ^1.6.2
  dart_style: ^1.2.2

dev_dependencies:
  analyzer: ^0.34.0
  test: ^1.5.1+1
  json_serializable: ^2.0.1
  json_annotation: ^2.0.0
  build_runner: ^1.1.2

executables:
  json2entity: cli
  j2e: cli

publish_to: 
  https://pub.dartlang.org